name: Publish DBN.Auth.Auth0.nupkg

on:
  workflow_dispatch:

jobs:
  publish_package:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: restore dependencies
      run: dotnet restore src/DBN.Auth.sln
    - name: pack package
      run: dotnet pack src/DBN.Auth.Auth0/DBN.Auth.Auth0.csproj -c release -p:NuspecFile=DBN.Auth.Auth0.nuspec
    - name: publish package
      run: dotnet nuget push src/DBN.Auth.Auth0/bin/release/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
